"use strict";
/**
 * Agenkit TypeScript - Minimal, composable interfaces for AI agents.
 *
 * @packageDocumentation
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.createPlanStep = exports.createPlan = exports.DefaultStepExecutor = exports.StepStatus = exports.PlanningAgent = exports.ConsensusAgent = exports.MultiAgentOrchestrator = exports.executeTask = exports.TaskTimeoutError = exports.Task = exports.createConversationalAgent = exports.ConversationalAgent = exports.createReActAgent = exports.ReActStopReason = exports.ReActAgent = exports.RouterPattern = exports.ParallelPattern = exports.SequentialPattern = exports.createAgentToolSimple = exports.createAgentTool = exports.OutputFormat = exports.AgentTool = exports.CritiqueFormat = exports.StopReason = exports.ReflectionAgent = exports.AnthropicAgent = exports.OpenAIAgent = exports.circuitBreaker = exports.CircuitState = exports.CircuitBreakerError = exports.CircuitBreakerMiddleware = exports.timeout = exports.TimeoutError = exports.TimeoutMiddleware = exports.retry = exports.RetryMiddleware = exports.BaseMiddleware = exports.applyMiddleware = exports.GrpcTransportError = exports.GrpcServer = exports.GrpcAgent = exports.WebSocketTransportError = exports.WebSocketAgent = exports.HttpTransportError = exports.HTTPAgent = exports.createCounterAgent = exports.createEchoAgent = exports.LocalAgent = exports.validateMessage = exports.createMessage = void 0;
exports.getPromptOptimizationDuration = exports.PromptOptimizer = exports.BayesianOptimizer = exports.optimizationResultToDict = exports.getOptimizationImprovement = exports.getOptimizationDuration = exports.RandomSearchOptimizer = exports.Optimizer = exports.SearchSpace = exports.regressionToDict = exports.isRegression = exports.Severity = exports.RegressionDetector = exports.interactionRecordFromDict = exports.interactionRecordToDict = exports.sessionRecordingFromDict = exports.sessionRecordingToDict = exports.getTotalLatency = exports.getSessionDuration = exports.InMemoryRecordingStorage = exports.FileRecordingStorage = exports.SessionReplay = exports.SessionRecorder = exports.compressionStatsToDict = exports.createCompressionStats = exports.CompressionMetrics = exports.ContextMetrics = exports.evaluateAgent = exports.resultToDict = exports.getSuccessRate = exports.Evaluator = exports.evaluateAgentQuality = exports.LatencyMetric = exports.QualityMetrics = exports.AccuracyMetric = exports.runBenchmark = exports.getBenchmarkByName = exports.getAllBenchmarks = exports.CodeGenerationBenchmark = exports.NeedleInHaystackBenchmark = exports.ReasoningBenchmark = exports.SimpleQABenchmark = exports.SignificanceLevel = exports.ABVariant = exports.ABTest = exports.canExecuteStep = exports.getPlanProgress = exports.hasPlanFailures = exports.isPlanComplete = exports.getNextSteps = void 0;
exports.getLoggerWithTrace = exports.getLoggingConfig = exports.configureLogging = exports.Logger = exports.LogLevel = exports.createMonitoredAgent = exports.MetricsMiddleware = exports.getMetricsUrl = exports.shutdownMetrics = exports.initMetrics = exports.createTracedAgent = exports.TracingMiddleware = exports.extractTraceContext = exports.injectTraceContext = exports.getTracer = exports.shutdownTracing = exports.initTracing = exports.createSelfConsistencyAgent = exports.SelfConsistencyAgent = exports.traceToDict = exports.getTraceDuration = exports.finalizeTrace = exports.addStepToTrace = exports.createReasoningTrace = exports.createReasoningStep = exports.ReasoningStepType = exports.ReasoningWithToolsAgent = exports.createGoal = exports.AutonomousAgent = exports.createMemoryEntry = exports.MemoryHierarchy = exports.LongTermMemory = exports.ShortTermMemory = exports.WorkingMemory = exports.createErrorRecord = exports.createMetricMeasurement = exports.MetricType = exports.SessionStatus = exports.MetricsCollector = exports.SessionResult = exports.promptOptimizationResultToDict = void 0;
// Core interfaces
var interfaces_1 = require("./core/interfaces");
Object.defineProperty(exports, "createMessage", { enumerable: true, get: function () { return interfaces_1.createMessage; } });
Object.defineProperty(exports, "validateMessage", { enumerable: true, get: function () { return interfaces_1.validateMessage; } });
// Adapters
var local_1 = require("./adapters/local");
Object.defineProperty(exports, "LocalAgent", { enumerable: true, get: function () { return local_1.LocalAgent; } });
Object.defineProperty(exports, "createEchoAgent", { enumerable: true, get: function () { return local_1.createEchoAgent; } });
Object.defineProperty(exports, "createCounterAgent", { enumerable: true, get: function () { return local_1.createCounterAgent; } });
// Transports
var http_1 = require("./transports/http");
Object.defineProperty(exports, "HTTPAgent", { enumerable: true, get: function () { return http_1.HTTPAgent; } });
Object.defineProperty(exports, "HttpTransportError", { enumerable: true, get: function () { return http_1.HttpTransportError; } });
var websocket_1 = require("./transports/websocket");
Object.defineProperty(exports, "WebSocketAgent", { enumerable: true, get: function () { return websocket_1.WebSocketAgent; } });
Object.defineProperty(exports, "WebSocketTransportError", { enumerable: true, get: function () { return websocket_1.WebSocketTransportError; } });
var grpc_1 = require("./transports/grpc");
Object.defineProperty(exports, "GrpcAgent", { enumerable: true, get: function () { return grpc_1.GrpcAgent; } });
Object.defineProperty(exports, "GrpcServer", { enumerable: true, get: function () { return grpc_1.GrpcServer; } });
Object.defineProperty(exports, "GrpcTransportError", { enumerable: true, get: function () { return grpc_1.GrpcTransportError; } });
// Middleware
var base_1 = require("./middleware/base");
Object.defineProperty(exports, "applyMiddleware", { enumerable: true, get: function () { return base_1.applyMiddleware; } });
Object.defineProperty(exports, "BaseMiddleware", { enumerable: true, get: function () { return base_1.BaseMiddleware; } });
var retry_1 = require("./middleware/retry");
Object.defineProperty(exports, "RetryMiddleware", { enumerable: true, get: function () { return retry_1.RetryMiddleware; } });
Object.defineProperty(exports, "retry", { enumerable: true, get: function () { return retry_1.retry; } });
var timeout_1 = require("./middleware/timeout");
Object.defineProperty(exports, "TimeoutMiddleware", { enumerable: true, get: function () { return timeout_1.TimeoutMiddleware; } });
Object.defineProperty(exports, "TimeoutError", { enumerable: true, get: function () { return timeout_1.TimeoutError; } });
Object.defineProperty(exports, "timeout", { enumerable: true, get: function () { return timeout_1.timeout; } });
var circuit_breaker_1 = require("./middleware/circuit-breaker");
Object.defineProperty(exports, "CircuitBreakerMiddleware", { enumerable: true, get: function () { return circuit_breaker_1.CircuitBreakerMiddleware; } });
Object.defineProperty(exports, "CircuitBreakerError", { enumerable: true, get: function () { return circuit_breaker_1.CircuitBreakerError; } });
Object.defineProperty(exports, "CircuitState", { enumerable: true, get: function () { return circuit_breaker_1.CircuitState; } });
Object.defineProperty(exports, "circuitBreaker", { enumerable: true, get: function () { return circuit_breaker_1.circuitBreaker; } });
// LLM Adapters
var openai_1 = require("./llm/openai");
Object.defineProperty(exports, "OpenAIAgent", { enumerable: true, get: function () { return openai_1.OpenAIAgent; } });
var anthropic_1 = require("./llm/anthropic");
Object.defineProperty(exports, "AnthropicAgent", { enumerable: true, get: function () { return anthropic_1.AnthropicAgent; } });
// Patterns
var reflection_1 = require("./patterns/reflection");
Object.defineProperty(exports, "ReflectionAgent", { enumerable: true, get: function () { return reflection_1.ReflectionAgent; } });
Object.defineProperty(exports, "StopReason", { enumerable: true, get: function () { return reflection_1.StopReason; } });
Object.defineProperty(exports, "CritiqueFormat", { enumerable: true, get: function () { return reflection_1.CritiqueFormat; } });
var agents_as_tools_1 = require("./patterns/agents-as-tools");
Object.defineProperty(exports, "AgentTool", { enumerable: true, get: function () { return agents_as_tools_1.AgentTool; } });
Object.defineProperty(exports, "OutputFormat", { enumerable: true, get: function () { return agents_as_tools_1.OutputFormat; } });
Object.defineProperty(exports, "createAgentTool", { enumerable: true, get: function () { return agents_as_tools_1.createAgentTool; } });
Object.defineProperty(exports, "createAgentToolSimple", { enumerable: true, get: function () { return agents_as_tools_1.createAgentToolSimple; } });
var orchestration_1 = require("./patterns/orchestration");
Object.defineProperty(exports, "SequentialPattern", { enumerable: true, get: function () { return orchestration_1.SequentialPattern; } });
Object.defineProperty(exports, "ParallelPattern", { enumerable: true, get: function () { return orchestration_1.ParallelPattern; } });
Object.defineProperty(exports, "RouterPattern", { enumerable: true, get: function () { return orchestration_1.RouterPattern; } });
var react_1 = require("./patterns/react");
Object.defineProperty(exports, "ReActAgent", { enumerable: true, get: function () { return react_1.ReActAgent; } });
Object.defineProperty(exports, "ReActStopReason", { enumerable: true, get: function () { return react_1.ReActStopReason; } });
Object.defineProperty(exports, "createReActAgent", { enumerable: true, get: function () { return react_1.createReActAgent; } });
var conversational_1 = require("./patterns/conversational");
Object.defineProperty(exports, "ConversationalAgent", { enumerable: true, get: function () { return conversational_1.ConversationalAgent; } });
Object.defineProperty(exports, "createConversationalAgent", { enumerable: true, get: function () { return conversational_1.createConversationalAgent; } });
var task_1 = require("./patterns/task");
Object.defineProperty(exports, "Task", { enumerable: true, get: function () { return task_1.Task; } });
Object.defineProperty(exports, "TaskTimeoutError", { enumerable: true, get: function () { return task_1.TimeoutError; } });
Object.defineProperty(exports, "executeTask", { enumerable: true, get: function () { return task_1.executeTask; } });
var multiagent_1 = require("./patterns/multiagent");
Object.defineProperty(exports, "MultiAgentOrchestrator", { enumerable: true, get: function () { return multiagent_1.MultiAgentOrchestrator; } });
Object.defineProperty(exports, "ConsensusAgent", { enumerable: true, get: function () { return multiagent_1.ConsensusAgent; } });
var planning_1 = require("./patterns/planning");
Object.defineProperty(exports, "PlanningAgent", { enumerable: true, get: function () { return planning_1.PlanningAgent; } });
Object.defineProperty(exports, "StepStatus", { enumerable: true, get: function () { return planning_1.StepStatus; } });
Object.defineProperty(exports, "DefaultStepExecutor", { enumerable: true, get: function () { return planning_1.DefaultStepExecutor; } });
Object.defineProperty(exports, "createPlan", { enumerable: true, get: function () { return planning_1.createPlan; } });
Object.defineProperty(exports, "createPlanStep", { enumerable: true, get: function () { return planning_1.createPlanStep; } });
Object.defineProperty(exports, "getNextSteps", { enumerable: true, get: function () { return planning_1.getNextSteps; } });
Object.defineProperty(exports, "isPlanComplete", { enumerable: true, get: function () { return planning_1.isPlanComplete; } });
Object.defineProperty(exports, "hasPlanFailures", { enumerable: true, get: function () { return planning_1.hasPlanFailures; } });
Object.defineProperty(exports, "getPlanProgress", { enumerable: true, get: function () { return planning_1.getPlanProgress; } });
Object.defineProperty(exports, "canExecuteStep", { enumerable: true, get: function () { return planning_1.canExecuteStep; } });
// Evaluation
var ab_testing_1 = require("./evaluation/ab-testing");
Object.defineProperty(exports, "ABTest", { enumerable: true, get: function () { return ab_testing_1.ABTest; } });
Object.defineProperty(exports, "ABVariant", { enumerable: true, get: function () { return ab_testing_1.ABVariant; } });
Object.defineProperty(exports, "SignificanceLevel", { enumerable: true, get: function () { return ab_testing_1.SignificanceLevel; } });
var benchmarks_1 = require("./evaluation/benchmarks");
Object.defineProperty(exports, "SimpleQABenchmark", { enumerable: true, get: function () { return benchmarks_1.SimpleQABenchmark; } });
Object.defineProperty(exports, "ReasoningBenchmark", { enumerable: true, get: function () { return benchmarks_1.ReasoningBenchmark; } });
Object.defineProperty(exports, "NeedleInHaystackBenchmark", { enumerable: true, get: function () { return benchmarks_1.NeedleInHaystackBenchmark; } });
Object.defineProperty(exports, "CodeGenerationBenchmark", { enumerable: true, get: function () { return benchmarks_1.CodeGenerationBenchmark; } });
Object.defineProperty(exports, "getAllBenchmarks", { enumerable: true, get: function () { return benchmarks_1.getAllBenchmarks; } });
Object.defineProperty(exports, "getBenchmarkByName", { enumerable: true, get: function () { return benchmarks_1.getBenchmarkByName; } });
Object.defineProperty(exports, "runBenchmark", { enumerable: true, get: function () { return benchmarks_1.runBenchmark; } });
var quality_metrics_1 = require("./evaluation/quality-metrics");
Object.defineProperty(exports, "AccuracyMetric", { enumerable: true, get: function () { return quality_metrics_1.AccuracyMetric; } });
Object.defineProperty(exports, "QualityMetrics", { enumerable: true, get: function () { return quality_metrics_1.QualityMetrics; } });
Object.defineProperty(exports, "LatencyMetric", { enumerable: true, get: function () { return quality_metrics_1.LatencyMetric; } });
Object.defineProperty(exports, "evaluateAgentQuality", { enumerable: true, get: function () { return quality_metrics_1.evaluateAgent; } });
var core_1 = require("./evaluation/core");
Object.defineProperty(exports, "Evaluator", { enumerable: true, get: function () { return core_1.Evaluator; } });
Object.defineProperty(exports, "getSuccessRate", { enumerable: true, get: function () { return core_1.getSuccessRate; } });
Object.defineProperty(exports, "resultToDict", { enumerable: true, get: function () { return core_1.resultToDict; } });
Object.defineProperty(exports, "evaluateAgent", { enumerable: true, get: function () { return core_1.evaluateAgent; } });
var context_metrics_1 = require("./evaluation/context-metrics");
Object.defineProperty(exports, "ContextMetrics", { enumerable: true, get: function () { return context_metrics_1.ContextMetrics; } });
Object.defineProperty(exports, "CompressionMetrics", { enumerable: true, get: function () { return context_metrics_1.CompressionMetrics; } });
Object.defineProperty(exports, "createCompressionStats", { enumerable: true, get: function () { return context_metrics_1.createCompressionStats; } });
Object.defineProperty(exports, "compressionStatsToDict", { enumerable: true, get: function () { return context_metrics_1.compressionStatsToDict; } });
var recorder_1 = require("./evaluation/recorder");
Object.defineProperty(exports, "SessionRecorder", { enumerable: true, get: function () { return recorder_1.SessionRecorder; } });
Object.defineProperty(exports, "SessionReplay", { enumerable: true, get: function () { return recorder_1.SessionReplay; } });
Object.defineProperty(exports, "FileRecordingStorage", { enumerable: true, get: function () { return recorder_1.FileRecordingStorage; } });
Object.defineProperty(exports, "InMemoryRecordingStorage", { enumerable: true, get: function () { return recorder_1.InMemoryRecordingStorage; } });
Object.defineProperty(exports, "getSessionDuration", { enumerable: true, get: function () { return recorder_1.getSessionDuration; } });
Object.defineProperty(exports, "getTotalLatency", { enumerable: true, get: function () { return recorder_1.getTotalLatency; } });
Object.defineProperty(exports, "sessionRecordingToDict", { enumerable: true, get: function () { return recorder_1.sessionRecordingToDict; } });
Object.defineProperty(exports, "sessionRecordingFromDict", { enumerable: true, get: function () { return recorder_1.sessionRecordingFromDict; } });
Object.defineProperty(exports, "interactionRecordToDict", { enumerable: true, get: function () { return recorder_1.interactionRecordToDict; } });
Object.defineProperty(exports, "interactionRecordFromDict", { enumerable: true, get: function () { return recorder_1.interactionRecordFromDict; } });
var regression_1 = require("./evaluation/regression");
Object.defineProperty(exports, "RegressionDetector", { enumerable: true, get: function () { return regression_1.RegressionDetector; } });
Object.defineProperty(exports, "Severity", { enumerable: true, get: function () { return regression_1.Severity; } });
Object.defineProperty(exports, "isRegression", { enumerable: true, get: function () { return regression_1.isRegression; } });
Object.defineProperty(exports, "regressionToDict", { enumerable: true, get: function () { return regression_1.regressionToDict; } });
var optimizer_1 = require("./evaluation/optimizer");
Object.defineProperty(exports, "SearchSpace", { enumerable: true, get: function () { return optimizer_1.SearchSpace; } });
Object.defineProperty(exports, "Optimizer", { enumerable: true, get: function () { return optimizer_1.Optimizer; } });
Object.defineProperty(exports, "RandomSearchOptimizer", { enumerable: true, get: function () { return optimizer_1.RandomSearchOptimizer; } });
Object.defineProperty(exports, "getOptimizationDuration", { enumerable: true, get: function () { return optimizer_1.getOptimizationDuration; } });
Object.defineProperty(exports, "getOptimizationImprovement", { enumerable: true, get: function () { return optimizer_1.getOptimizationImprovement; } });
Object.defineProperty(exports, "optimizationResultToDict", { enumerable: true, get: function () { return optimizer_1.optimizationResultToDict; } });
var bayesian_optimizer_1 = require("./evaluation/bayesian-optimizer");
Object.defineProperty(exports, "BayesianOptimizer", { enumerable: true, get: function () { return bayesian_optimizer_1.BayesianOptimizer; } });
var prompt_optimizer_1 = require("./evaluation/prompt-optimizer");
Object.defineProperty(exports, "PromptOptimizer", { enumerable: true, get: function () { return prompt_optimizer_1.PromptOptimizer; } });
Object.defineProperty(exports, "getPromptOptimizationDuration", { enumerable: true, get: function () { return prompt_optimizer_1.getPromptOptimizationDuration; } });
Object.defineProperty(exports, "promptOptimizationResultToDict", { enumerable: true, get: function () { return prompt_optimizer_1.promptOptimizationResultToDict; } });
var metrics_1 = require("./evaluation/metrics");
Object.defineProperty(exports, "SessionResult", { enumerable: true, get: function () { return metrics_1.SessionResult; } });
Object.defineProperty(exports, "MetricsCollector", { enumerable: true, get: function () { return metrics_1.MetricsCollector; } });
Object.defineProperty(exports, "SessionStatus", { enumerable: true, get: function () { return metrics_1.SessionStatus; } });
Object.defineProperty(exports, "MetricType", { enumerable: true, get: function () { return metrics_1.MetricType; } });
Object.defineProperty(exports, "createMetricMeasurement", { enumerable: true, get: function () { return metrics_1.createMetricMeasurement; } });
Object.defineProperty(exports, "createErrorRecord", { enumerable: true, get: function () { return metrics_1.createErrorRecord; } });
var memory_1 = require("./patterns/memory");
Object.defineProperty(exports, "WorkingMemory", { enumerable: true, get: function () { return memory_1.WorkingMemory; } });
Object.defineProperty(exports, "ShortTermMemory", { enumerable: true, get: function () { return memory_1.ShortTermMemory; } });
Object.defineProperty(exports, "LongTermMemory", { enumerable: true, get: function () { return memory_1.LongTermMemory; } });
Object.defineProperty(exports, "MemoryHierarchy", { enumerable: true, get: function () { return memory_1.MemoryHierarchy; } });
Object.defineProperty(exports, "createMemoryEntry", { enumerable: true, get: function () { return memory_1.createMemoryEntry; } });
var autonomous_1 = require("./patterns/autonomous");
Object.defineProperty(exports, "AutonomousAgent", { enumerable: true, get: function () { return autonomous_1.AutonomousAgent; } });
Object.defineProperty(exports, "createGoal", { enumerable: true, get: function () { return autonomous_1.createGoal; } });
var reasoning_with_tools_1 = require("./patterns/reasoning-with-tools");
Object.defineProperty(exports, "ReasoningWithToolsAgent", { enumerable: true, get: function () { return reasoning_with_tools_1.ReasoningWithToolsAgent; } });
Object.defineProperty(exports, "ReasoningStepType", { enumerable: true, get: function () { return reasoning_with_tools_1.ReasoningStepType; } });
Object.defineProperty(exports, "createReasoningStep", { enumerable: true, get: function () { return reasoning_with_tools_1.createReasoningStep; } });
Object.defineProperty(exports, "createReasoningTrace", { enumerable: true, get: function () { return reasoning_with_tools_1.createReasoningTrace; } });
Object.defineProperty(exports, "addStepToTrace", { enumerable: true, get: function () { return reasoning_with_tools_1.addStepToTrace; } });
Object.defineProperty(exports, "finalizeTrace", { enumerable: true, get: function () { return reasoning_with_tools_1.finalizeTrace; } });
Object.defineProperty(exports, "getTraceDuration", { enumerable: true, get: function () { return reasoning_with_tools_1.getTraceDuration; } });
Object.defineProperty(exports, "traceToDict", { enumerable: true, get: function () { return reasoning_with_tools_1.traceToDict; } });
// Reasoning Techniques
var self_consistency_1 = require("./techniques/reasoning/self-consistency");
Object.defineProperty(exports, "SelfConsistencyAgent", { enumerable: true, get: function () { return self_consistency_1.SelfConsistencyAgent; } });
Object.defineProperty(exports, "createSelfConsistencyAgent", { enumerable: true, get: function () { return self_consistency_1.createSelfConsistencyAgent; } });
// Observability
var observability_1 = require("./observability");
Object.defineProperty(exports, "initTracing", { enumerable: true, get: function () { return observability_1.initTracing; } });
Object.defineProperty(exports, "shutdownTracing", { enumerable: true, get: function () { return observability_1.shutdownTracing; } });
Object.defineProperty(exports, "getTracer", { enumerable: true, get: function () { return observability_1.getTracer; } });
Object.defineProperty(exports, "injectTraceContext", { enumerable: true, get: function () { return observability_1.injectTraceContext; } });
Object.defineProperty(exports, "extractTraceContext", { enumerable: true, get: function () { return observability_1.extractTraceContext; } });
Object.defineProperty(exports, "TracingMiddleware", { enumerable: true, get: function () { return observability_1.TracingMiddleware; } });
Object.defineProperty(exports, "createTracedAgent", { enumerable: true, get: function () { return observability_1.createTracedAgent; } });
Object.defineProperty(exports, "initMetrics", { enumerable: true, get: function () { return observability_1.initMetrics; } });
Object.defineProperty(exports, "shutdownMetrics", { enumerable: true, get: function () { return observability_1.shutdownMetrics; } });
Object.defineProperty(exports, "getMetricsUrl", { enumerable: true, get: function () { return observability_1.getMetricsUrl; } });
Object.defineProperty(exports, "MetricsMiddleware", { enumerable: true, get: function () { return observability_1.MetricsMiddleware; } });
Object.defineProperty(exports, "createMonitoredAgent", { enumerable: true, get: function () { return observability_1.createMonitoredAgent; } });
Object.defineProperty(exports, "LogLevel", { enumerable: true, get: function () { return observability_1.LogLevel; } });
Object.defineProperty(exports, "Logger", { enumerable: true, get: function () { return observability_1.Logger; } });
Object.defineProperty(exports, "configureLogging", { enumerable: true, get: function () { return observability_1.configureLogging; } });
Object.defineProperty(exports, "getLoggingConfig", { enumerable: true, get: function () { return observability_1.getLoggingConfig; } });
Object.defineProperty(exports, "getLoggerWithTrace", { enumerable: true, get: function () { return observability_1.getLoggerWithTrace; } });
