"""Parity matrix generator.

Combines feature manifest and test counts to generate comprehensive
parity matrix showing feature coverage across all languages (see
check_regression.MIN_FEATURE_COUNTS for the current list).
"""

import json
import re
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

try:
    from jinja2 import Environment, FileSystemLoader
except ImportError:
    print("Error: jinja2 required. Install with: pip install jinja2", file=sys.stderr)
    sys.exit(1)

try:
    from scripts.parity.check_regression import MIN_FEATURE_COUNTS
except ImportError:
    # Running as a script rather than a package (e.g. `python matrix_generator.py`
    # from inside scripts/parity/) -- fall back to a path-relative import.
    sys.path.insert(0, str(Path(__file__).parent))
    from check_regression import MIN_FEATURE_COUNTS  # type: ignore[import-not-found]

# check_regression.MIN_FEATURE_COUNTS is the actively-maintained 9-language
# list (its floors are recalibrated every time a language ships new
# features). This module used to hardcode its own 6-language list, so
# C#/Java/Scala were invisible in the generated docs even after a clean
# regenerate -- see #918/#913.
LANGUAGES = list(MIN_FEATURE_COUNTS.keys())
CATEGORIES = ["patterns", "middleware", "llm_adapters", "memory", "techniques"]


def load_feature_manifest() -> dict[str, Any]:
    """Load feature manifest generated by feature scanner.

    Returns:
        Feature manifest dict

    Raises:
        FileNotFoundError: If manifest doesn't exist
    """
    manifest_path = Path("feature-manifest.json")

    if not manifest_path.exists():
        raise FileNotFoundError(
            f"Feature manifest not found at {manifest_path}. "
            "Run: python scripts/parity/feature_scanner.py"
        )

    with manifest_path.open() as f:
        return json.load(f)


def load_test_report() -> dict[str, Any] | None:
    """Load test parity report if it exists.

    Returns:
        Test report dict or None if doesn't exist
    """
    report_path = Path("test-parity-report.json")

    if not report_path.exists():
        print(f"Warning: Test report not found at {report_path}", file=sys.stderr)
        return None

    with report_path.open() as f:
        return json.load(f)


def generate_feature_matrix(
    feature_manifest: dict[str, Any], test_report: dict[str, Any] | None
) -> str:
    """Generate feature parity matrix markdown.

    Args:
        feature_manifest: Feature detection results
        test_report: Test count results (optional)

    Returns:
        Markdown string for parity matrix
    """
    # Prepare template environment
    template_dir = Path("scripts/parity/templates")
    env = Environment(loader=FileSystemLoader(template_dir))
    template = env.get_template("matrix.md.j2")

    # Build matrix data
    matrix_data = build_matrix_data(feature_manifest, test_report)

    # Render template
    return template.render(**matrix_data)


def build_matrix_data(
    feature_manifest: dict[str, Any], test_report: dict[str, Any] | None
) -> dict[str, Any]:
    """Build data structure for matrix template.

    Args:
        feature_manifest: Feature detection results
        test_report: Test count results (optional)

    Returns:
        Dict with all data needed for template rendering
    """
    languages = LANGUAGES
    categories = CATEGORIES

    # Collect all unique features across all languages
    all_features: dict[str, set[str]] = {cat: set() for cat in categories}

    for lang in languages:
        lang_features = feature_manifest["languages"].get(lang, {})
        for category in categories:
            features = lang_features.get(category, [])
            all_features[category].update(features)

    # Build matrix rows
    matrix_rows = []

    for category in categories:
        for feature in sorted(all_features[category]):
            row = {
                "category": category,
                "feature": feature,
                "languages": {},
            }

            # Check which languages have this feature
            for lang in languages:
                lang_features = feature_manifest["languages"].get(lang, {})
                features_in_lang = lang_features.get(category, [])

                if feature in features_in_lang:
                    row["languages"][lang] = "✅"
                else:
                    row["languages"][lang] = "❌"

            matrix_rows.append(row)

    # Build summary statistics
    summary_stats = []

    for lang in languages:
        lang_data = feature_manifest["languages"].get(lang, {})
        total_features = feature_manifest["summary"]["total"].get(lang, 0)

        # Get test count if available
        test_count = 0
        if test_report and "languages" in test_report:
            lang_tests = test_report["languages"].get(lang, {})
            test_count = lang_tests.get("total", 0)

        # Calculate parity percentage (relative to Python)
        python_total = feature_manifest["summary"]["total"].get("python", 1)
        parity_pct = (total_features / python_total * 100) if python_total > 0 else 0

        summary_stats.append(
            {
                "language": lang,
                "total_features": total_features,
                "parity_percent": round(parity_pct, 1),
                "test_count": test_count,
            }
        )

    # Build category summaries
    category_summaries = []

    for category in categories:
        category_counts = {}
        for lang in languages:
            lang_features = feature_manifest["languages"].get(lang, {})
            count = len(lang_features.get(category, []))
            category_counts[lang] = count

        category_summaries.append({"category": category, "counts": category_counts})

    return {
        "generated_at": datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC"),
        "languages": languages,
        "categories": categories,
        "matrix_rows": matrix_rows,
        "summary_stats": summary_stats,
        "category_summaries": category_summaries,
        "has_test_data": test_report is not None,
    }


def write_matrix(matrix_md: str, output_path: Path) -> None:
    """Write matrix markdown to file.

    Args:
        matrix_md: Matrix markdown content
        output_path: Path to output file
    """
    # Ensure directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w") as f:
        f.write(matrix_md)

    print(f"✓ Feature matrix written to: {output_path}")


# Matches both "**Generated**: <ts>" (FEATURE_MATRIX.md) and
# "Generated: <ts>" (GAPS_ANALYSIS.md) -- the one line in each file that is a
# function of wall-clock time rather than of feature-manifest.json's
# content, and so must be normalized out before a byte-for-byte diff. Without
# this, --check would fail on every run even when nothing substantive
# changed, which is the opposite of what a staleness gate should do.
_GENERATED_TIMESTAMP_LINE = re.compile(r"^\*{0,2}Generated\*{0,2}:.*$", re.MULTILINE)


def _normalize_generated_timestamp(content: str) -> str:
    return _GENERATED_TIMESTAMP_LINE.sub("Generated: <normalized>", content)


def check_matrix_current(matrix_md: str, gap_md: str) -> list[str]:
    """Diff freshly generated content against the committed files.

    Returns a list of human-readable diffs; empty when both files are
    current. This is #902's core mechanism: feature-manifest.json is already
    regenerated fresh on every CI run, but nothing has ever compared that
    fresh output to the committed docs/parity/*.md -- which is how
    GAPS_ANALYSIS.md went five months stale while CI stayed green throughout.

    Args:
        matrix_md: Freshly generated FEATURE_MATRIX.md content.
        gap_md: Freshly generated GAPS_ANALYSIS.md content.

    Returns:
        Unified diffs, one per stale file; empty if both are current.
    """
    import difflib

    diffs = []
    for label, fresh, path in (
        ("docs/parity/FEATURE_MATRIX.md", matrix_md, Path("docs/parity/FEATURE_MATRIX.md")),
        ("docs/parity/GAPS_ANALYSIS.md", gap_md, Path("docs/parity/GAPS_ANALYSIS.md")),
    ):
        if not path.exists():
            diffs.append(f"{label}: does not exist -- run matrix_generator.py to create it")
            continue

        committed = _normalize_generated_timestamp(path.read_text())
        rendered = _normalize_generated_timestamp(fresh)

        if committed != rendered:
            diff = "\n".join(
                difflib.unified_diff(
                    committed.splitlines(),
                    rendered.splitlines(),
                    fromfile=f"{label} (committed)",
                    tofile=f"{label} (freshly generated)",
                    lineterm="",
                )
            )
            diffs.append(diff)

    return diffs


def generate_gap_analysis(feature_manifest: dict[str, Any]) -> str:
    """Generate gap analysis showing missing features per language.

    Args:
        feature_manifest: Feature detection results

    Returns:
        Markdown string for gap analysis
    """
    languages = LANGUAGES
    categories = CATEGORIES

    # Use Python as baseline
    python_features = feature_manifest["languages"]["python"]

    gap_analysis = []
    gap_analysis.append("# Feature Gap Analysis\n")
    gap_analysis.append(f"Generated: {datetime.now(UTC).strftime('%Y-%m-%d %H:%M:%S UTC')}\n")
    gap_analysis.append("\n")
    gap_analysis.append(
        "This report shows features present in Python (baseline) but missing in other languages.\n"
    )
    gap_analysis.append("\n")

    for lang in languages:
        if lang == "python":
            continue

        gap_analysis.append(f"## {lang.title()} Gaps\n")
        gap_analysis.append("\n")

        lang_features = feature_manifest["languages"][lang]
        has_gaps = False

        for category in categories:
            python_items = set(python_features.get(category, []))
            lang_items = set(lang_features.get(category, []))

            missing = python_items - lang_items

            if missing:
                has_gaps = True
                gap_analysis.append(f"### Missing {category.replace('_', ' ').title()}\n")
                gap_analysis.append("\n")

                for item in sorted(missing):
                    gap_analysis.append(f"- {item}\n")

                gap_analysis.append("\n")

        if not has_gaps:
            gap_analysis.append("*No gaps - full parity with Python!* ✅\n")
            gap_analysis.append("\n")

    return "".join(gap_analysis)


def _report_check_result(diffs: list[str]) -> int:
    if diffs:
        print("✗ Generated parity docs are stale:")
        print()
        for diff in diffs:
            print(diff)
            print()
        print("=" * 70)
        print("Run: uv run python scripts/parity/matrix_generator.py")
        print("Then commit the regenerated docs/parity/*.md files.")
        print("=" * 70)
        return 1
    print("✓ docs/parity/FEATURE_MATRIX.md and GAPS_ANALYSIS.md are current")
    return 0


def main() -> int:
    """Main entry point.

    Returns:
        Exit code (0 = success, 1 = error)
    """
    check_only = "--check" in sys.argv

    print("=" * 70)
    print("Parity Matrix Generator")
    print("=" * 70)
    print()

    try:
        # Load data
        print("Loading feature manifest...", end=" ")
        feature_manifest = load_feature_manifest()
        print("✓")

        print("Loading test report...", end=" ")
        test_report = load_test_report()
        if test_report:
            print("✓")
        else:
            print("⚠ (not found - continuing without test data)")
        print()

        # Generate feature matrix
        print("Generating feature matrix...", end=" ")
        matrix_md = generate_feature_matrix(feature_manifest, test_report)
        print("✓")

        # Generate gap analysis
        print("Generating gap analysis...", end=" ")
        gap_md = generate_gap_analysis(feature_manifest)
        print("✓")
        print()

        if check_only:
            return _report_check_result(check_matrix_current(matrix_md, gap_md))

        # Write feature matrix
        matrix_path = Path("docs/parity/FEATURE_MATRIX.md")
        write_matrix(matrix_md, matrix_path)

        # Write gap analysis
        gap_path = Path("docs/parity/GAPS_ANALYSIS.md")
        write_matrix(gap_md, gap_path)

        print()
        print("=" * 70)
        print("✓ Matrix generation complete!")
        print("=" * 70)
        print()
        print("View reports:")
        print(f"  - {matrix_path}")
        print(f"  - {gap_path}")
        print()

        return 0

    except Exception as e:
        print(f"\n✗ Error: {e}", file=sys.stderr)
        import traceback

        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
