"""Parity matrix generator.

Combines feature manifest and test counts to generate comprehensive
parity matrix showing feature coverage across all 6 languages.
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    from jinja2 import Environment, FileSystemLoader
except ImportError:
    print("Error: jinja2 required. Install with: pip install jinja2", file=sys.stderr)
    sys.exit(1)


def load_feature_manifest() -> dict[str, Any]:
    """Load feature manifest generated by feature scanner.

    Returns:
        Feature manifest dict

    Raises:
        FileNotFoundError: If manifest doesn't exist
    """
    manifest_path = Path("feature-manifest.json")

    if not manifest_path.exists():
        raise FileNotFoundError(
            f"Feature manifest not found at {manifest_path}. "
            "Run: python scripts/parity/feature_scanner.py"
        )

    with manifest_path.open() as f:
        return json.load(f)


def load_test_report() -> dict[str, Any] | None:
    """Load test parity report if it exists.

    Returns:
        Test report dict or None if doesn't exist
    """
    report_path = Path("test-parity-report.json")

    if not report_path.exists():
        print(f"Warning: Test report not found at {report_path}", file=sys.stderr)
        return None

    with report_path.open() as f:
        return json.load(f)


def generate_feature_matrix(
    feature_manifest: dict[str, Any], test_report: dict[str, Any] | None
) -> str:
    """Generate feature parity matrix markdown.

    Args:
        feature_manifest: Feature detection results
        test_report: Test count results (optional)

    Returns:
        Markdown string for parity matrix
    """
    # Prepare template environment
    template_dir = Path("scripts/parity/templates")
    env = Environment(loader=FileSystemLoader(template_dir))
    template = env.get_template("matrix.md.j2")

    # Build matrix data
    matrix_data = build_matrix_data(feature_manifest, test_report)

    # Render template
    return template.render(**matrix_data)


def build_matrix_data(
    feature_manifest: dict[str, Any], test_report: dict[str, Any] | None
) -> dict[str, Any]:
    """Build data structure for matrix template.

    Args:
        feature_manifest: Feature detection results
        test_report: Test count results (optional)

    Returns:
        Dict with all data needed for template rendering
    """
    languages = ["python", "go", "typescript", "rust", "cpp", "zig"]
    categories = ["patterns", "middleware", "llm_adapters", "memory"]

    # Collect all unique features across all languages
    all_features: dict[str, set[str]] = {cat: set() for cat in categories}

    for lang in languages:
        lang_features = feature_manifest["languages"].get(lang, {})
        for category in categories:
            features = lang_features.get(category, [])
            all_features[category].update(features)

    # Build matrix rows
    matrix_rows = []

    for category in categories:
        for feature in sorted(all_features[category]):
            row = {
                "category": category,
                "feature": feature,
                "languages": {},
            }

            # Check which languages have this feature
            for lang in languages:
                lang_features = feature_manifest["languages"].get(lang, {})
                features_in_lang = lang_features.get(category, [])

                if feature in features_in_lang:
                    row["languages"][lang] = "✅"
                else:
                    row["languages"][lang] = "❌"

            matrix_rows.append(row)

    # Build summary statistics
    summary_stats = []

    for lang in languages:
        lang_data = feature_manifest["languages"].get(lang, {})
        total_features = feature_manifest["summary"]["total"].get(lang, 0)

        # Get test count if available
        test_count = 0
        if test_report and "languages" in test_report:
            lang_tests = test_report["languages"].get(lang, {})
            test_count = lang_tests.get("total", 0)

        # Calculate parity percentage (relative to Python)
        python_total = feature_manifest["summary"]["total"].get("python", 1)
        parity_pct = (total_features / python_total * 100) if python_total > 0 else 0

        summary_stats.append(
            {
                "language": lang,
                "total_features": total_features,
                "parity_percent": round(parity_pct, 1),
                "test_count": test_count,
            }
        )

    # Build category summaries
    category_summaries = []

    for category in categories:
        category_counts = {}
        for lang in languages:
            lang_features = feature_manifest["languages"].get(lang, {})
            count = len(lang_features.get(category, []))
            category_counts[lang] = count

        category_summaries.append({"category": category, "counts": category_counts})

    return {
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        "languages": languages,
        "categories": categories,
        "matrix_rows": matrix_rows,
        "summary_stats": summary_stats,
        "category_summaries": category_summaries,
        "has_test_data": test_report is not None,
    }


def write_matrix(matrix_md: str, output_path: Path) -> None:
    """Write matrix markdown to file.

    Args:
        matrix_md: Matrix markdown content
        output_path: Path to output file
    """
    # Ensure directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w") as f:
        f.write(matrix_md)

    print(f"✓ Feature matrix written to: {output_path}")


def generate_gap_analysis(feature_manifest: dict[str, Any]) -> str:
    """Generate gap analysis showing missing features per language.

    Args:
        feature_manifest: Feature detection results

    Returns:
        Markdown string for gap analysis
    """
    languages = ["python", "go", "typescript", "rust", "cpp", "zig"]
    categories = ["patterns", "middleware", "llm_adapters", "memory"]

    # Use Python as baseline
    python_features = feature_manifest["languages"]["python"]

    gap_analysis = []
    gap_analysis.append("# Feature Gap Analysis\n")
    gap_analysis.append(
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}\n"
    )
    gap_analysis.append("\n")
    gap_analysis.append(
        "This report shows features present in Python (baseline) but missing in other languages.\n"
    )
    gap_analysis.append("\n")

    for lang in languages:
        if lang == "python":
            continue

        gap_analysis.append(f"## {lang.title()} Gaps\n")
        gap_analysis.append("\n")

        lang_features = feature_manifest["languages"][lang]
        has_gaps = False

        for category in categories:
            python_items = set(python_features.get(category, []))
            lang_items = set(lang_features.get(category, []))

            missing = python_items - lang_items

            if missing:
                has_gaps = True
                gap_analysis.append(f"### Missing {category.replace('_', ' ').title()}\n")
                gap_analysis.append("\n")

                for item in sorted(missing):
                    gap_analysis.append(f"- {item}\n")

                gap_analysis.append("\n")

        if not has_gaps:
            gap_analysis.append("*No gaps - full parity with Python!* ✅\n")
            gap_analysis.append("\n")

    return "".join(gap_analysis)


def main() -> int:
    """Main entry point.

    Returns:
        Exit code (0 = success, 1 = error)
    """
    print("=" * 70)
    print("Parity Matrix Generator")
    print("=" * 70)
    print()

    try:
        # Load data
        print("Loading feature manifest...", end=" ")
        feature_manifest = load_feature_manifest()
        print("✓")

        print("Loading test report...", end=" ")
        test_report = load_test_report()
        if test_report:
            print("✓")
        else:
            print("⚠ (not found - continuing without test data)")
        print()

        # Generate feature matrix
        print("Generating feature matrix...", end=" ")
        matrix_md = generate_feature_matrix(feature_manifest, test_report)
        print("✓")

        # Write feature matrix
        matrix_path = Path("docs/parity/FEATURE_MATRIX.md")
        write_matrix(matrix_md, matrix_path)

        # Generate gap analysis
        print("Generating gap analysis...", end=" ")
        gap_md = generate_gap_analysis(feature_manifest)
        print("✓")

        # Write gap analysis
        gap_path = Path("docs/parity/GAPS_ANALYSIS.md")
        write_matrix(gap_md, gap_path)

        print()
        print("=" * 70)
        print("✓ Matrix generation complete!")
        print("=" * 70)
        print()
        print(f"View reports:")
        print(f"  - {matrix_path}")
        print(f"  - {gap_path}")
        print()

        return 0

    except Exception as e:
        print(f"\n✗ Error: {e}", file=sys.stderr)
        import traceback

        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
