# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import agent_pb2 as proto_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """AgentService defines the gRPC service for agent communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Process = channel.unary_unary(
                '/agenkit.AgentService/Process',
                request_serializer=proto_dot_agent__pb2.Request.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.Response.FromString,
                _registered_method=True)
        self.ProcessStream = channel.unary_stream(
                '/agenkit.AgentService/ProcessStream',
                request_serializer=proto_dot_agent__pb2.Request.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.StreamChunk.FromString,
                _registered_method=True)
        self.BidirectionalStream = channel.stream_stream(
                '/agenkit.AgentService/BidirectionalStream',
                request_serializer=proto_dot_agent__pb2.Request.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.Response.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """AgentService defines the gRPC service for agent communication
    """

    def Process(self, request, context):
        """Process sends a request and receives a single response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessStream(self, request, context):
        """ProcessStream sends a request and receives a stream of response chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BidirectionalStream(self, request_iterator, context):
        """BidirectionalStream enables full-duplex streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Process': grpc.unary_unary_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=proto_dot_agent__pb2.Request.FromString,
                    response_serializer=proto_dot_agent__pb2.Response.SerializeToString,
            ),
            'ProcessStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessStream,
                    request_deserializer=proto_dot_agent__pb2.Request.FromString,
                    response_serializer=proto_dot_agent__pb2.StreamChunk.SerializeToString,
            ),
            'BidirectionalStream': grpc.stream_stream_rpc_method_handler(
                    servicer.BidirectionalStream,
                    request_deserializer=proto_dot_agent__pb2.Request.FromString,
                    response_serializer=proto_dot_agent__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agenkit.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agenkit.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """AgentService defines the gRPC service for agent communication
    """

    @staticmethod
    def Process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agenkit.AgentService/Process',
            proto_dot_agent__pb2.Request.SerializeToString,
            proto_dot_agent__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agenkit.AgentService/ProcessStream',
            proto_dot_agent__pb2.Request.SerializeToString,
            proto_dot_agent__pb2.StreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BidirectionalStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/agenkit.AgentService/BidirectionalStream',
            proto_dot_agent__pb2.Request.SerializeToString,
            proto_dot_agent__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
